package com.serwylo.trivia.questions.factories

import com.serwylo.trivia.questions.GeneratedQuestion

/**
 * Some questions are arranged in their data file such that they can only be generated when they know the values of other
 * data items. For example, the questions may be randomly generated by combining multiple items.
 * Therefore, we can't produce questions until each line has been parsed.
 */
abstract class BatchQuestionFactory extends QuestionFactory {

	private List<Map<String, String>> cachedData = []

	protected List<Map<String, String>> getCachedData() {
		return this.cachedData
	}

	@Override
	protected List<GeneratedQuestion> parseQuestions(Map<String, String> values) {

		cachedData.add( values )
		return []

	}

	abstract protected List<GeneratedQuestion> generateQuestions()

	public List<GeneratedQuestion> getQuestions() {

		// Populates the cachedData thing...
		super.getQuestions()

		return generateQuestions()

	}

}
